### ISSUE TITLE
压缩失败！报错：This endpoint does not exist.

### ISSUE THREAD

**Issue by keyasu** [zhanyuzhang/super-tinypng#7]
[/Users/123/Downloads/蒙版_slices/蒙版@2x.png]：压缩失败！报错：This endpoint does not exist.
[/Users/123/Downloads/蒙版_slices/蒙版@3x.png]：压缩失败！报错：This endpoint does not exist.

以前正常使用的, 今天报错这个, 想了解一下具体问题

**Comment by AndySkaura** [comment]
#8 接口变了

**Comment by benweng** [comment]
> #8 接口变了

很棒！

**Comment by whsldbgdl428** [comment]
接口变成什么了,这个包有升级吗

**Comment by Suposing** [comment]
改一下接口就能使用了

**Comment by yanzuliu001** [comment]
接口改成什么了

**Comment by johnzian** [comment]
作者比较忙，可能没时间看
如果安装了全局包
前往 C:\Users\你的window用户名\AppData\Roaming\npm\node_modules\super-tinypng\index.js
 path: '/web/shrink',改为
 path: '/backend/opt/shrink',
感谢作者和pull request的用户

**Comment by zhanyuzhang** [comment]
@AndySkaura 感谢大佬的 PR，已 merge，大家重新安装一下即可正常使用哈 
```
npm i super-tinypng -g 
```
